---
- name: restart step-ca
  systemd:
    name: step-ca.service
    state: restarted

- name: print CA cert fingerprint
  debug:
    msg: 'Fingerprint of the root CA: {{ stepca_rootca_fingerprint.stdout }}'
