- name: Include ca_server vars
  include_vars: '{{ item }}'
  loop:
  - ../../../roles/ca_server/defaults/main.yml
  - ../../../roles/ca_server/vars/main.yml
  - '../../../roles/ca_server/vars/{{ ansible_os_family }}.yml'

- name: Testing keys are present
  copy:
    src: '{{ item }}'
    dest: '{{ stepca_home }}/'
    owner: '{{ stepca_user }}'
    group: '{{ stepca_user }}'
    mode: 0600
  become: yes
  become_user: '{{ stepca_user }}'
  loop:
  - files/molecule_jwk_key
  - files/molecule_x5c_key

- name: Testing password file is present
  copy:
    concent: molecule-test
    dest: '{{ stepca_home }}/molecule_passfile'
    owner: '{{ stepca_user }}'
    group: '{{ stepca_user }}'
    mode: 0600
  become: yes
  become_user: '{{ stepca_user }}'

- name: Create test provisioners
  ariosthephoenix.smallstep.ca_provisioner: '{{ item }}'
  become: yes
  become_user: '{{ stepca_user }}'
  loop:
  - name: molecule-JWK
    type: JWK
    jwk_key_files: '{{ stepca_home }}/molecule_jwk_key'
    jwk_password_file: '{{ stepca_home }}/molecule_passfile'
  - name: molecule-OIDC
    type: OIDC
    oidc_client_id: 1087160488420-8qt7bavg3qesdhs6it824mhnfgcfe8il.apps.googleusercontent.com
    oidc_configuration_endpoint: https://accounts.google.com/.well-known/openid-configuration
    oidc_admin_email:
      - mariano@smallstep.com
      - max@smallstep.com
    oidc_domain: smallstep.com
  - name: molecule-Amazon
    type: AWS
    aws_account: 123456789
    instance_age: 1h
  - name: molecule-Google
    type: GCP
    gcp_service_account:
      - 1234567890-compute@developer.gserviceaccount.com
      - 9876543210-compute@developer.gserviceaccount.com
    gcp_project:
      - identity
      - accounting
  - name: molecule-Azure
    type: Azure
    azure_tenant: bc9043e2-b645-4c1c-a87a-78f8644bfe57
    azure_resource_group:
      - identity
      - accounting
  - name: molecule-ACME
    type: ACME
  - name: molecule-x5c
    type: X5C
    # Key file must already exist on the remote host
    x5c_root_file: '{{ stepca_home }}/molecule_x5c_key'
  - name: molecule-sshpop
    type: SSHPOP

- name: Remove test provisioners
  maxhoesel.smallstep.ca_provisioner:
    name: '{{ item }}'
    state: absent
  become: yes
  become_user: '{{ stepca_user }}'
  loop:
  - molecule-JWK
  - molecule-OIDC
  - molecule-Amazon
  - molecule-Google
  - molecule-Azure
  - molcule-ACME
  - molecue-x5c
  - molecule-sshpop
