---
- name: Verify that step_ca_name and step_ca_root_password are set # noqa no-log-password
  assert:
    that:
      - step_ca_name is defined
      - step_ca_name | length > 0
      - step_ca_root_password is defined
      - step_ca_root_password | length > 0
    fail_msg: step_ca_name and step_ca_root_password must both be set
  when: ansible_version.string is version('2.11.1', '<')

- name: Set existing root cert
  set_fact:
    step_ca_existing_root_file: "{{ step_ca_path }}/.step_ca_root.crt"
    step_ca_delete_temp_root: true
  when: >
    step_ca_existing_root is defined and
    step_ca_existing_root_file is not defined

- name: Set existing root key
  set_fact:
    step_ca_existing_key_temp_file: "{{ step_ca_path }}/.step_ca_root.key"
  when: >
    (step_ca_existing_key is defined and
    step_ca_existing_key_file is not defined) or
    (step_ca_existing_key_password is defined and
    step_ca_existing_key_file is defined)

- name: Set existing root key password file
  set_fact:
    step_ca_existing_key_password_file: "{{ step_ca_path }}/.password_existing_root.txt"
  when: >
    step_ca_existing_key_password is defined

- name: Verify existing root cert/key
  assert:
    that:
      - step_ca_existing_root_file | length > 0
      - (step_ca_existing_key_file is defined and step_ca_existing_key_file | length > 0) or (step_ca_existing_key_temp_file is defined and step_ca_existing_key_temp_file | length > 0)
    fail_msg: Existing root cert/key variables must be passed as a group
  when: >
    step_ca_existing_root_file is defined or
    step_ca_existing_key_file is defined or
    step_ca_existing_key_temp_file is defined

- name: Verify RA variables
  assert:
    that:
      - step_ca_ra | length > 0
      - step_ca_ra_issuer | length > 0
      - step_ca_ra_credentials_file | length > 0
    fail_msg: RA variables must be passed as a group
  when: >
    step_ca_ra is defined or
    step_ca_ra_issuer is defined or
    step_ca_ra_credentials_file is defined

- name: set step_ca_intermediate_password
  set_fact:
    step_ca_intermediate_password: "{{ step_ca_root_password }}"
  when: not step_ca_intermediate_password is defined
  no_log: yes

- name: Install step_cli # always run this, to ensure our cli version is also up-to-date
  include_role:
    name: maxhoesel.smallstep.step_cli
