---
- name: Verify that step_ca_name and step_ca_root_password are set # noqa no-log-password
  assert:
    that:
      - step_ca_name is defined
      - step_ca_name | length > 0
      - step_ca_root_password is defined
      - step_ca_root_password | length > 0
    fail_msg: step_ca_name and step_ca_root_password must both be set
  when: ansible_version.string is version('2.11.1', '<')

# TODO: Include assert for `step_ca_existing_key_password`
- name: Verify existing root cert/key
  assert:
    that:
      - step_ca_existing_root_file | length > 0
      - step_ca_existing_key_file | length > 0
    fail_msg: Existing root cert/key variables must be passed as a group
  when: >
    step_ca_existing_root_file is defined or
    step_ca_existing_key_file is defined

- name: Verify existing root key/password
  assert:
    that:
      - step_ca_existing_key_file | length > 0
    fail_msg: Existing root key must be passed if its password is defined
  when: step_ca_existing_key_password is defined

# TODO: Remove deprecation warning and add assert in `Verify existing root cert/key`
- name: Check that password is provided
# Deprecation warning 'hack'
  ignore_errors: yes
  fail:
    msg: >-
      [Warning] Root key password is not provided for remote key. This will later be disallowed in future versions.
      Either use unencrypted local (on controller) key, or use an encrypted key, either local or remote.
  when: >
    step_ca_existing_key == 'remote' and
    step_ca_existing_key_password is not defined

- name: Verify RA variables
  assert:
    that:
      - step_ca_ra | length > 0
      - step_ca_ra_issuer | length > 0
      - step_ca_ra_credentials_file | length > 0
    fail_msg: RA variables must be passed as a group
  when: >
    step_ca_ra is defined or
    step_ca_ra_issuer is defined or
    step_ca_ra_credentials_file is defined

- name: set step_ca_intermediate_password
  set_fact:
    step_ca_intermediate_password: "{{ step_ca_root_password }}"
  when: not step_ca_intermediate_password is defined
  no_log: yes

- name: Install step_cli # always run this, to ensure our cli version is also up-to-date
  include_role:
    name: maxhoesel.smallstep.step_cli
