- name: Service unit file is installed
  template:
    src: step-ca.service.j2
    dest: /etc/systemd/system/step-ca.service
    owner: root
    group: root
    mode: 0644
  notify: restart step-ca

- name: Service is enabled and running
  systemd:
    daemon_reload: yes
    name: step-ca.service
    enabled: yes
    state: started
