- name: requirements are installed [Debian]
  apt:
    name:
    - xz-utils
    update_cache: yes
  retries: 3
  delay: 3

- name: step is installed [Debian]
  apt:
    deb: 'https://github.com/smallstep/cli/releases/download/v{{ stepclient_version }}/step-cli_{{ stepclient_version }}_amd64.deb'
  retries: 3
  delay: 3
  when: stepclient_current_version.stdout != stepclient_version
