# These pipes squelch the "command not found" error message if the binary isn't installed yet.
# Instead, they return "", which we simply use as our version string.
# Not the cleanest solution, but it's simple and works well.
- name: Get current version
  shell: "{{ stepclient_executable_path }}/step version | cut -d' ' -f 2 | cut -d'/' -f 2 | awk 'FNR == 1'" # noqa 306
  changed_when: no
  register: stepclient_current_version

- block:
  - name: Get latest release information
    uri:
      url: https://api.github.com/repos/smallstep/cli/releases/latest
      body_format: json
      return_content: yes
    register: stepclient_latest_release
    delegate_to: localhost
    run_once: yes
    retries: 3
    delay: 3
  - name: Set release tag
    set_fact:
      stepclient_version: '{{ (stepclient_latest_release.json.tag_name)[1:] }}'
  when: stepclient_version == 'latest'

- name: Insatll step cli
  include: 'install_{{ ansible_os_family }}.yml'
