---
- name: Create step-ca servers
  hosts: server-*
  roles:
  - role: maxhoesel.smallstep.ca_server
    stepca_name: Molecule-Test
    stepca_dns_name: localhost
    stepca_root_password: molecule-test
    stepca_intermediate_password: molecule-test
