---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server-ubuntu-20
    image: "geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
  - name: server-ubuntu-18
    image: "geerlingguy/docker-ubuntu1804-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
  - name: server-debian-10
    image: "geerlingguy/docker-debian10-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
  - name: server-debian-9
    image: "geerlingguy/docker-debian9-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
  - name: server-centos-8
    image: "geerlingguy/docker-centos8-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: ${TESTENV_VERBOSE:-false}
  env:
    ANSIBLE_KEEP_REMOTE_FILES: ${TESTENV_KEEP_REMOTE:-false}
    ANSIBLE_COLLECTIONS_PATH: ${TESTENV_COLLECTIONS:-~/.ansible/collections:/usr/share/ansible/collections}
  inventory:
    group_vars:
      all:
        testing_password: molecule-test
verifier:
  name: ansible
