- name: Look for existing step-cli binary [RedHat/Other]
  stat:
    path: "{{ step_cli_executable_path }}/step"
  register: step_cli_present
- name: Get currently installed step-cli version [RedHat/Other]
  shell: >
    set -o pipefail &&
    {{ step_cli_executable_path }}/step version | cut -d' ' -f 2 | cut -d'/' -f 2 | awk 'FNR == 1'
  args:
    executable: /bin/bash
  changed_when: no
  check_mode: no
  register: step_cli_installed_version
  when: step_cli_present.stat.exists

- block:
    - name: Download and extract step-cli archive [RedHat/Other]
      unarchive:
        src: "https://github.com/smallstep/cli/releases/download/v{{ step_cli_version }}/step_linux_{{ step_cli_version }}_amd64.tar.gz"
        dest: /tmp
        remote_src: yes
      retries: 3
      delay: 3
    - name: Install step-cli binary [RedHat/Other]
      shell: >
        set -o pipefail &&
        cp /tmp/step_{{ step_cli_version }}/bin/* {{ step_cli_executable_path }}/
  always:
    - name: Remove step release archive [RedHat/Other]
      file:
        path: "/tmp/step_{{ step_cli_version }}"
        state: absent
  when: (step_cli_installed_version.stdout) | default("") != step_cli_version
