---
# tasks file for step_acme_cert
- include: check.yml

- name: Look for existing certificate
  stat:
    path: "{{ step_acme_cert_certfile.path }}"
  register: step_acme_cert_current_cert

- name: Check if certificate is expired
  community.crypto.x509_certificate_info:
    path: "{{ step_acme_cert_certfile.path }}"
    valid_at:
      now: "+0s"
  register: step_acme_cert_certinfo
  when: step_acme_cert_current_cert.stat.exists

- include: get_cert.yml
  when: not step_acme_cert_current_cert.stat.exists or not step_acme_cert_certinfo.valid_at.now

- include: renewal.yml
