---
name: CI Roles
on: [push, pull_request]

defaults:
  run:
    working-directory: "smallstep"

jobs:
  lint:
    name: lint ${{ matrix.role }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2
        with:
          path: smallstep
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install test dependencies
        run: pip3 install yamllint ansible-lint ansible
      - name: Build collection
        run: ansible-galaxy collection build
      - name: Install collection
        run: ansible-galaxy collection install maxhoesel-smallstep-*.tar.gz
      - name: Lint code
        run: ansible-lint
